-- JD FRIENDLY REAL SOCIAL DATABASE
-- Run this entire file once in Supabase SQL Editor.

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  username text unique,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamptz default now()
);

create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending','accepted','rejected')),
  created_at timestamptz default now(),
  unique(sender_id, receiver_id)
);

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  friend_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz default now(),
  unique(user_id, friend_id)
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_one uuid not null references auth.users(id) on delete cascade,
  user_two uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  message_text text,
  photo_url text,
  created_at timestamptz default now(),
  check (message_text is not null or photo_url is not null)
);

create index if not exists messages_conversation_idx
on public.messages(conversation_id, created_at);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamptz default now()
);

insert into public.games(name, description)
select 'Tic-Tac-Toe', 'Classic two-player game'
where not exists (
  select 1 from public.games where name = 'Tic-Tac-Toe'
);

insert into public.games(name, description)
select 'Connect Four', 'Classic four-in-a-row game'
where not exists (
  select 1 from public.games where name = 'Connect Four'
);

alter table public.profiles enable row level security;
alter table public.friend_requests enable row level security;
alter table public.friendships enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.games enable row level security;

drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "requests_select_involved" on public.friend_requests;
create policy "requests_select_involved"
on public.friend_requests for select
to authenticated
using (sender_id = auth.uid() or receiver_id = auth.uid());

drop policy if exists "requests_insert_sender" on public.friend_requests;
create policy "requests_insert_sender"
on public.friend_requests for insert
to authenticated
with check (sender_id = auth.uid());

drop policy if exists "requests_update_receiver" on public.friend_requests;
create policy "requests_update_receiver"
on public.friend_requests for update
to authenticated
using (receiver_id = auth.uid())
with check (receiver_id = auth.uid());

drop policy if exists "friendships_select_own" on public.friendships;
create policy "friendships_select_own"
on public.friendships for select
to authenticated
using (user_id = auth.uid() or friend_id = auth.uid());

drop policy if exists "friendships_insert_own" on public.friendships;
create policy "friendships_insert_own"
on public.friendships for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "conversations_select_members" on public.conversations;
create policy "conversations_select_members"
on public.conversations for select
to authenticated
using (user_one = auth.uid() or user_two = auth.uid());

drop policy if exists "conversations_insert_members" on public.conversations;
create policy "conversations_insert_members"
on public.conversations for insert
to authenticated
with check (user_one = auth.uid() or user_two = auth.uid());

drop policy if exists "messages_select_members" on public.messages;
create policy "messages_select_members"
on public.messages for select
to authenticated
using (
  exists (
    select 1
    from public.conversations c
    where c.id = conversation_id
      and (c.user_one = auth.uid() or c.user_two = auth.uid())
  )
);

drop policy if exists "messages_insert_sender_member" on public.messages;
create policy "messages_insert_sender_member"
on public.messages for insert
to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1
    from public.conversations c
    where c.id = conversation_id
      and (c.user_one = auth.uid() or c.user_two = auth.uid())
  )
);

drop policy if exists "games_select_authenticated" on public.games;
create policy "games_select_authenticated"
on public.games for select
to authenticated
using (true);

alter publication supabase_realtime add table public.messages;
